### ISSUE TITLE
[Feature Request] Can you add the Xades signature support ?

### ISSUE THREAD

**Issue by p4535992** [AlessioScarfone/Java-Digital-Signature#13]
Can you add the Xades signature support ?
P.S. Ty for this little project.

**Comment by AlessioScarfone** [comment]
Hi @p4535992 ,
you are free to extend the software as you like.
Unfortunately I no longer have a digital signature token so I can't add functionality at the moment.

**Comment by p4535992** [comment]
np ty for this little gem
