### ISSUE TITLE
How to specify a file path for a digital certificate?

### ISSUE THREAD

**Issue by NoahCardoza** [AlessioScarfone/Java-Digital-Signature#2]
This project seems to exclusively read from a card reader. Is there anyway to read a cert from a file?

**Comment by AlessioScarfone** [comment]
Hi @NoahCardoza. No there isn't, the project aims only at integration with PKCS#11 signature via token/card reader.

**Comment by NoahCardoza** [comment]
Currently I'm looking into other options besides PDFs since they seem to be so random when it comes to the spec across different versions. But, should I be forces to work with PDFs, would it be easy to adjust this to work with a file?

While ultimately it will need to work with a card reader, I'd like to load certs/keys from a file for testing as I won't have access to a CAC. I'd also probably use `smartcardio` since that's what my clients suggested. While I have a little Java experience, if needed I think I could figure it out if I use this project as a starting point.

**Comment by miguelius** [comment]
You could try softhsm2!

**Comment by NoahCardoza** [comment]
Alright, I'll give it a look! Thanks!
