### ISSUE TITLE
Token access failed

### ISSUE THREAD

**Issue by milesvor** [AlessioScarfone/Java-Digital-Signature#3]
Windows 10 pro 64 bit
Java version 1.8.0_291
Usb token di aruba correttamente installato

Quando viene chiesto l'inserimento della password digitando "java -jar signed.jar -i" inserisco il codice pin della smartcard
Viene restituito l'errore "token acccess failed"
Lo stesso errore quando cerco di siglare con l'estensione chrome.
Cosa guardare per analizzare meglio la problematica?
Grazie

**Comment by milesvor** [comment]
Letto thread precedente: utilizzando java 8.181 funziona.

**Comment by AlessioScarfone** [comment]
> Letto thread precedente: utilizzando java 8.181 funziona.
> 

Ciao milesvor,
visto che hai risolto chiudo l'issue. 🙂

**Comment by milesvor** [comment]
Funziona molto bene. Come potrei fare a passargli una lista di files invece
di lanciare n volte il programma?
Grazie

Il Sab 29 Mag 2021, 09:33 Alessio Scarfone ***@***.***> ha
scritto:

**Comment by AlessioScarfone** [comment]
Non supporta la lista ma solo un singolo file. Puoi automatizzare il tutto con uno script che chiama n volte oppure sei libero di modificare il codice per aggiungere la funzionalità.

Purtroppo io non ho più un token per sviluppare ed estendere il software.

**Comment by milesvor** [comment]
Ok grazie

Il Sab 29 Mag 2021, 10:29 Alessio Scarfone ***@***.***> ha
scritto:

**Comment by to-jbm** [comment]
Hi
I have the same issue
I'm using gemalto usb token
Windows 10 pro 64 bit
java version "1.8.0_181"
